spring:
  datasource:
    url: jdbc:mysql://localhost:3306/member?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dlscjf12
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: govlepel@$&